apiVersion: v1
kind: Service
metadata:
  name: simplewebapp-service
  namespace: simplewebapp
  labels:
    app: SimpleWebApp
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: SimpleWebApp
  type: LoadBalancer